#cloud_journey/docker-compose.yml
version: '3'
services:
  app:
    build: demo_project
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./demo_project:/app
    ports:
      - "8000:8000"
